In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
b = np.array([[1,2],[3,4]])
b


array([[1, 2],
       [3, 4]])

In [4]:
a.shape

(4,)

In [5]:
b.shape

(2, 2)

In [6]:
c = a.reshape(4,1
)
c

array([[1],
       [2],
       [3],
       [4]])

In [8]:
c.shape

(4, 1)